version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install deps and run parser
          command: |
            sudo pip install pipenv
            pipenv run python parser.py
      - run:
          name: Archive PDF and related data in git
          command: |
            ./git_archive.sh
      - save_cache:
          key: v1-deps-{{ checksum "Pipfile.lock" }}
          paths: "~/.local/share/virtualenvs/"

workflows:
   version: 2
   build_on_commit:
     jobs:
        - build
   twice_a_day:
     triggers:
       - schedule:
           cron: "0 0,12 * * *"  # Twice a day at 00:00 and 12:00
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
