version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: 1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cd:0e:48:63:be:a2:0e:f7:03:04:e7:7b:d8:51:8e:71"
      - checkout
      - restore_cache:
          key: v2-deps-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install requirements (poppler and pipenv)
          command: |
            sudo apt-get update
            sudo apt-get install poppler-utils -y
            pip install -U pip
            pip install pipenv
      - run:
          name: install dependencies and parse
          command: pipenv install
      - save_cache:
          key: v2-deps-{{ checksum "Pipfile.lock" }}
          paths: .venv
      - run:
          name: Download and parse
          command: pipenv run python parser.py
      - run:
          name: Archive PDF and related data in git
          command: ./git_archive.sh

workflows:
   version: 2
   build_on_commit:
     jobs:
        - build
   twice_a_day:
     triggers:
       - schedule:
           cron: "0 0,12 * * *"  # Twice a day at 00:00 and 12:00
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
